/*
* ============================================================================
*  Name     : HelpView.h
*  Part of  : 
*  Created  : 7/12/2004 by Ezhil
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: PurpleAce
* ============================================================================
*/


#ifndef HELPVIEW_H
#define HELPVIEW_H


// INCLUDES
#include <aknview.h>

//const TUid KHelpViewId = {7};

// FORWARD DECLARATIONS
class CHelpContainer;
class CRippleVaultAppUi;


/*
*  CHelpView view class. 
*/

class CHelpView : public CAknView
    {
    public: // Constructors and destructor

		void ConstructL();
        ~CHelpView();

    public: // Functions from base classes

        TUid Id() const;
        void HandleCommandL(TInt aCommand);
        void HandleClientRectChange();
		CRippleVaultAppUi* iPhotosAppUi;

    private:

        void DoActivateL(const TVwsViewId& aPrevViewId,TUid aCustomMessageId,
        const TDesC8& aCustomMessage);
        void DoDeactivate();

    private: // Data		
        CHelpContainer* iHelpContainer;				
    };

#endif



// End of File

