/*
* ============================================================================
*  Name     : CSecureApp from SecureApp.cpp
*  Part of  : Secure
*  Created  : 8/6/2005 by Ezhil
*  Implementation notes:
*
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: Purpleace
* ============================================================================
*/

// INCLUDE FILES
#include    "SecureApp.h"
#include    "SecureDocument.h"

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CSecureApp::AppDllUid()
// Returns application UID
// ---------------------------------------------------------
//
TUid CSecureApp::AppDllUid() const
    {
    return KUidSecure;
    }

   
// ---------------------------------------------------------
// CSecureApp::CreateDocumentL()
// Creates CSecureDocument object
// ---------------------------------------------------------
//
CApaDocument* CSecureApp::CreateDocumentL()
    {
    return CSecureDocument::NewL( *this );
    }

// ================= OTHER EXPORTED FUNCTIONS ==============
//
// ---------------------------------------------------------
// NewApplication() 
// Constructs CSecureApp
// Returns: created application object
// ---------------------------------------------------------
//
EXPORT_C CApaApplication* NewApplication()
    {
    return new CSecureApp;
    }

// ---------------------------------------------------------
// E32Dll(TDllReason) 
// Entry point function for EPOC Apps
// Returns: KErrNone: No error
// ---------------------------------------------------------
//
GLDEF_C TInt E32Dll( TDllReason )
    {
    return KErrNone;
    }

// End of File  

